// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/pokemon_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5685321046494141879),
      name: 'PokemonModel',
      lastPropertyId: const IdUid(6, 2166950043824786698),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 918682145612930721),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4803206127298089724),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'types', srcEntity: 'PokemonType', srcField: '')
      ]),
  ModelEntity(
      id: const IdUid(2, 233661857342884176),
      name: 'PokemonType',
      lastPropertyId: const IdUid(3, 1793455330400559476),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3782757766193214143),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5116698193566954543),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1793455330400559476),
            name: 'typeId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 7551634076504768048),
            relationTarget: 'PokemonModel')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 233661857342884176),
      lastIndexId: const IdUid(1, 7551634076504768048),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3135257458733323192,
        4473566844846191212,
        5460921481502637312,
        2166950043824786698
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    PokemonModel: EntityDefinition<PokemonModel>(
        model: _entities[0],
        toOneRelations: (PokemonModel object) => [],
        toManyRelations: (PokemonModel object) => {
              RelInfo<PokemonType>.toOneBacklink(
                      3, object.id, (PokemonType srcObject) => srcObject.type):
                  object.types
            },
        getId: (PokemonModel object) => object.id,
        setId: (PokemonModel object, int id) {
          object.id = id;
        },
        objectToFB: (PokemonModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PokemonModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));
          InternalToManyAccess.setRelInfo(
              object.types,
              store,
              RelInfo<PokemonType>.toOneBacklink(
                  3, object.id, (PokemonType srcObject) => srcObject.type),
              store.box<PokemonModel>());
          return object;
        }),
    PokemonType: EntityDefinition<PokemonType>(
        model: _entities[1],
        toOneRelations: (PokemonType object) => [object.type],
        toManyRelations: (PokemonType object) => {},
        getId: (PokemonType object) => object.id,
        setId: (PokemonType object, int id) {
          object.id = id;
        },
        objectToFB: (PokemonType object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.type.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PokemonType(
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.type.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.type.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [PokemonModel] entity fields to define ObjectBox queries.
class PokemonModel_ {
  /// see [PokemonModel.id]
  static final id =
      QueryIntegerProperty<PokemonModel>(_entities[0].properties[0]);

  /// see [PokemonModel.name]
  static final name =
      QueryStringProperty<PokemonModel>(_entities[0].properties[1]);
}

/// [PokemonType] entity fields to define ObjectBox queries.
class PokemonType_ {
  /// see [PokemonType.id]
  static final id =
      QueryIntegerProperty<PokemonType>(_entities[1].properties[0]);

  /// see [PokemonType.name]
  static final name =
      QueryStringProperty<PokemonType>(_entities[1].properties[1]);

  /// see [PokemonType.type]
  static final type =
      QueryRelationToOne<PokemonType, PokemonModel>(_entities[1].properties[2]);
}
